RecMedia = RecMedia or {}

RecMedia["VHS_EZClippyTalkShow"] = {
	itemDisplayName = "VHS: Clippy talk show",
	title = "VHS: Clippy talk show",
	subtitle = nil,
	author = "Unknow",
	extra = "What an idea ?",
	spawning = 0,
	category = "Retail-VHS",
	lines = {
		{ text = "RM_126f3c7f-2df5-40e6-b7b9-7981fcf5f788", r = 0.2, g = 0.6, b = 0.1, codes = "BOR-1" },
		{ text = "Hello folks !", r = 0.9, g = 0.6, b = 0.0, codes = "BOR+1" },
		{ text = "Oh, hello ?", r = 0.20, g = 0.60, b = 0.40, codes = "BOR-1" },
		{ text = "Today, I whill show you a very simple trick", r = 0.9, g = 0.6, b = 0.0, codes = "BOR+1" },
		{ text = "Who this guy ?", r = 0.20, g = 0.60, b = 0.40, codes = "BOR-1" },
		{ text = "You see, you take 1 paperclip...", r = 0.9, g = 0.6, b = 0.0, codes = "BOR+1" },
		{ text = "Call the security !", r = 0.20, g = 0.60, b = 0.40, codes = "BOR-1" },
		{ text = "All your magazine ...", r = 0.9, g = 0.6, b = 0.0, codes = "BOR+1" },
		{ text = "And it's done !", r = 0.9, g = 0.6, b = 0.0, codes = "RCP=MakeCompleteFishingMag" },
		{ text = "My Goodness ...", r = 0.20, g = 0.60, b = 0.40, codes = "RCP=MakeCompleteFishingMag" },
		{ text = "Yeah, I know, what an idea ...", r = 0.9, g = 0.6, b = 0.0, codes = "RCP=MakeCompleteHuntingMag" },
		{ text = "Why didn't We think of that? ...", r = 0.9, g = 0.6, b = 0.0, codes = "RCP=MakeCompleteMetalworkMag" },
		{ text = "Look at this ...", r = 0.9, g = 0.6, b = 0.0, codes = "RCP=MakeCompleteCookingMag" },
		{ text = "Beautiful isn't it ?", r = 0.9, g = 0.6, b = 0.0, codes = "RCP=MakeCompleteElectronicMag" },
		{ text = "We can free so many spaces ...", r = 0.20, g = 0.60, b = 0.40, codes = "RCP=MakeCompleteEngineerMag" },
		{ text = "And the next time ...", r = 0.9, g = 0.6, b = 0.0, codes = "RCP=MakeCompleteRadioMag" },
		{ text = "RM_1c98b1e8-5e1c-485c-aaf5-eff85e99c7b8", r = 1.00, g = 1.00, b = 1.00, codes = "BOR-1" },
	},
};